CREATE DATABASE IF NOT EXISTS marketlink CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE marketlink;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS shop_product_prices, market_products, shops, favorites, reviews, order_items, orders, products, markets, users;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE shops (
 id INT AUTO_INCREMENT PRIMARY KEY,
 shop_name VARCHAR(150) NOT NULL,
 shop_type ENUM('vegetable','fruit','meat','chicken','grocery','supermarket','farmers_market') NOT NULL,
 address TEXT NOT NULL,
 area VARCHAR(100) NOT NULL,
 latitude DECIMAL(10,8) NOT NULL,
 longitude DECIMAL(11,8) NOT NULL,
 phone VARCHAR(40),
 source_note VARCHAR(255),
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 username VARCHAR(100) NOT NULL,
 email VARCHAR(100) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('customer','farmer','admin') NOT NULL DEFAULT 'customer',
 phone VARCHAR(30), address TEXT,
 status ENUM('active','pending','suspended') NOT NULL DEFAULT 'active',
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE markets (
 id INT AUTO_INCREMENT PRIMARY KEY,
 market_name VARCHAR(100) NOT NULL,
 address TEXT NOT NULL,
 operating_days VARCHAR(100) NOT NULL,
 timings VARCHAR(100) NOT NULL,
 latitude DECIMAL(10,8) NOT NULL,
 longitude DECIMAL(11,8) NOT NULL,
 map_provider VARCHAR(30) DEFAULT 'OpenStreetMap'
);

CREATE TABLE products (
 id INT AUTO_INCREMENT PRIMARY KEY,
 farmer_id INT NOT NULL,
 name VARCHAR(100) NOT NULL,
 category VARCHAR(60) NOT NULL,
 description TEXT,
 price DECIMAL(10,2) NOT NULL,
 unit VARCHAR(30) NOT NULL,
 stock_quantity INT NOT NULL DEFAULT 0,
 image_url VARCHAR(500) DEFAULT NULL,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (farmer_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE market_products (
 market_id INT NOT NULL,
 product_id INT NOT NULL,
 PRIMARY KEY(market_id,product_id),
 FOREIGN KEY(market_id) REFERENCES markets(id) ON DELETE CASCADE,
 FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE shop_product_prices (
 id INT AUTO_INCREMENT PRIMARY KEY,
 shop_id INT NOT NULL,
 product_id INT NOT NULL,
 price DECIMAL(10,2) NOT NULL,
 unit VARCHAR(30) NOT NULL,
 price_note VARCHAR(120) DEFAULT 'Demo listing price - confirm with shop',
 UNIQUE KEY uq_shop_product(shop_id,product_id),
 FOREIGN KEY(shop_id) REFERENCES shops(id) ON DELETE CASCADE,
 FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE orders (
 id INT AUTO_INCREMENT PRIMARY KEY,
 customer_id INT NOT NULL,
 total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
 order_status VARCHAR(30) NOT NULL DEFAULT 'placed',
 pickup_market_id INT,
 pickup_time DATETIME,
 order_date DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(customer_id) REFERENCES users(id),
 FOREIGN KEY(pickup_market_id) REFERENCES markets(id) ON DELETE SET NULL
);

CREATE TABLE order_items (
 id INT AUTO_INCREMENT PRIMARY KEY,
 order_id INT NOT NULL,
 product_id INT NOT NULL,
 quantity INT NOT NULL,
 unit_price DECIMAL(10,2) NOT NULL,
 FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,
 FOREIGN KEY(product_id) REFERENCES products(id)
);

CREATE TABLE reviews (
 id INT AUTO_INCREMENT PRIMARY KEY,
 product_id INT NOT NULL,
 customer_id INT NOT NULL,
 rating INT NOT NULL,
 comment TEXT,
 review_date DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,
 FOREIGN KEY(customer_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE favorites (
 id INT AUTO_INCREMENT PRIMARY KEY,
 customer_id INT NOT NULL,
 product_id INT,
 farmer_id INT,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(customer_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,
 FOREIGN KEY(farmer_id) REFERENCES users(id) ON DELETE CASCADE
);

DELETE FROM users WHERE email IN ('admin@marketlink.com','farmer@marketlink.com','customer@marketlink.com');

INSERT INTO users(username,email,password_hash,role,status) VALUES
('Admin','admin@marketlink.com','$2y$12$cn2aQytXqakbxQ6cGTBb7esRgRhayddsgIxxod9onRKVm7LNPZ/Q.','admin','active'),
('Green Valley Farm','farmer@marketlink.com','$2y$12$cn2aQytXqakbxQ6cGTBb7esRgRhayddsgIxxod9onRKVm7LNPZ/Q.','farmer','active'),
('Demo Customer','customer@marketlink.com','$2y$12$cn2aQytXqakbxQ6cGTBb7esRgRhayddsgIxxod9onRKVm7LNPZ/Q.','customer','active');

INSERT INTO markets(market_name,address,operating_days,timings,latitude,longitude) VALUES
('Karachi Vegetable Market','Sabzi Mandi Rd, New Sabzi Mandi, Karachi','Daily','06:00 - 20:00',24.94440,67.12480),
('Karachi Fruit Market','Fruit Market, New Sabzi Mandi, Karachi','Daily','06:00 - 20:00',24.94410,67.12430),
('Karachi Meat Market','Liaquatabad, Karachi','Daily','10:00 - 20:00',24.90580,67.03960),
('Karachi Chicken Market','Gulshan-e-Iqbal / Gulzar-e-Hijri, Karachi','Daily','09:00 - 23:30',24.92360,67.09890),
('Karachi Grocery & Dairy Market','Shaheed-e-Millat / North Nazimabad, Karachi','Daily','10:00 - 23:00',24.87480,67.06620),
('Karachi Farmers Market','DHA Phase 6 / Bahria Town, Karachi','Selected days','09:00 - 20:30',24.80140,67.05210);

INSERT INTO shops(shop_name,shop_type,address,area,latitude,longitude,phone,source_note) VALUES
('Sabzi Mandi - Super Highway','vegetable','Sabzi Mandi Rd, New Sabzi Mandi, Karachi','New Sabzi Mandi',24.94440,67.12480,'+923478222228','Public business listing; wholesale vegetable market'),
('FRUIT MARKET','fruit','158/15 Godhra Rd, Sector 5-J, New Karachi, Karachi','New Karachi',24.96620,67.06150,NULL,'Public business listing; produce market'),
('Piyara Pakistan Goods Transport Company','fruit','Fruit Market, New Sabzi Mandi, Karachi','New Sabzi Mandi',24.94410,67.12430,NULL,'Public business listing; fruit and vegetable wholesaler'),
('Meat Market, Liaquatabad','meat','Block 2 Liaquatabad, Karachi','Liaquatabad',24.90580,67.03960,NULL,'Public business listing; meat wholesaler'),
('SADAT POULTRY PRODUCT','chicken','S.T, Block 6 Gulshan-e-Iqbal, Karachi','Gulshan-e-Iqbal',24.92360,67.09890,'+922134973576','Public business listing; chicken shop'),
('Bismillah Rizwan Wholesale Chicken Centre','chicken','Kehkashan Homes, Gulzar-e-Hijri, Karachi','Gulzar-e-Hijri',24.95800,67.15370,NULL,'Public business listing; wholesale chicken centre'),
('Naheed Supermarket','supermarket','156-157 Main Shaheed-e-Millat Rd, Block 3, Karachi','Shaheed-e-Millat',24.87480,67.06620,'+9221111624333','Public business listing; supermarket'),
('Garden Super Mart','supermarket','182, 2 G3 Nishtar Rd, Garden East, Karachi','Garden East',24.88360,67.02390,'+923334444624','Public business listing; supermarket'),
('Hydri Super Market','supermarket','F-97, Block B North Nazimabad, Karachi','North Nazimabad',24.94220,67.03190,'+922136723291','Public business listing; supermarket'),
('Karachi Farmers Market (Shop)','farmers_market','14C Lane 7 Bukhari Commercial Area, DHA Phase 6, Karachi','DHA Phase 6',24.80140,67.05210,'+923025631417','Public business listing; natural goods/farmers market shop'),
('FRASHO','farmers_market','Commercial, Mark-I Building, Precinct-1 Bahria Town Karachi','Bahria Town',25.00470,67.31300,'+923001828131','Public business listing; produce market');


INSERT INTO products(farmer_id,name,category,description,price,unit,stock_quantity,image_url) VALUES
(2,'Tomatoes (Tamatar)','Vegetables','Fresh Tomatoes (Tamatar) sourced from local growers and prepared for market pickup.',180,'kg',50,'assets/img/products/tomatoes-tamatar.jpg'),
(2,'Potatoes (Aloo)','Vegetables','Fresh Potatoes (Aloo) sourced from local growers and prepared for market pickup.',90,'kg',50,'assets/img/products/potatoes-aloo.jpg'),
(2,'Red Onions (Pyaaz)','Vegetables','Fresh Red Onions (Pyaaz) sourced from local growers and prepared for market pickup.',120,'kg',50,'assets/img/products/red-onions-pyaaz.jpg'),
(2,'Cucumber (Kheera)','Vegetables','Fresh Cucumber (Kheera) sourced from local growers and prepared for market pickup.',110,'kg',50,'assets/img/products/cucumber-kheera.jpg'),
(2,'Carrots (Gajar)','Vegetables','Fresh Carrots (Gajar) sourced from local growers and prepared for market pickup.',190,'kg',50,'assets/img/products/carrots-gajar.jpg'),
(2,'Capsicum (Shimla Mirch)','Vegetables','Fresh Capsicum (Shimla Mirch) sourced from local growers and prepared for market pickup.',280,'kg',50,'assets/img/products/capsicum-shimla-mirch.jpg'),
(2,'Green Chillies (Hari Mirch)','Vegetables','Fresh Green Chillies (Hari Mirch) sourced from local growers and prepared for market pickup.',250,'kg',50,'assets/img/products/green-chillies-hari-mirch.jpg'),
(2,'Lemon (Nimbu)','Vegetables','Fresh Lemon (Nimbu) sourced from local growers and prepared for market pickup.',150,'kg',50,'assets/img/products/lemon-nimbu.jpg'),
(2,'Garlic (Lehsan)','Vegetables','Fresh Garlic (Lehsan) sourced from local growers and prepared for market pickup.',350,'kg',50,'assets/img/products/garlic-lehsan.jpg'),
(2,'Ginger (Adrak)','Vegetables','Fresh Ginger (Adrak) sourced from local growers and prepared for market pickup.',320,'kg',50,'assets/img/products/ginger-adrak.jpg'),
(2,'Lady Finger (Bhindi)','Vegetables','Fresh Lady Finger (Bhindi) sourced from local growers and prepared for market pickup.',180,'kg',50,'assets/img/products/lady-finger-bhindi.jpg'),
(2,'Brinjal (Baingan)','Vegetables','Fresh Brinjal (Baingan) sourced from local growers and prepared for market pickup.',150,'kg',50,'assets/img/products/brinjal-baingan.jpg'),
(2,'Bitter Gourd (Karela)','Vegetables','Fresh Bitter Gourd (Karela) sourced from local growers and prepared for market pickup.',170,'kg',50,'assets/img/products/bitter-gourd-karela.jpg'),
(2,'Bottle Gourd (Lauki)','Vegetables','Fresh Bottle Gourd (Lauki) sourced from local growers and prepared for market pickup.',120,'kg',50,'assets/img/products/bottle-gourd-lauki.jpg'),
(2,'Pumpkin (Kaddu)','Vegetables','Fresh Pumpkin (Kaddu) sourced from local growers and prepared for market pickup.',130,'kg',50,'assets/img/products/pumpkin-kaddu.jpg'),
(2,'Green Peas (Matar)','Vegetables','Fresh Green Peas (Matar) sourced from local growers and prepared for market pickup.',380,'kg',50,'assets/img/products/green-peas-matar.jpg'),
(2,'Cabbage (Band Gobhi)','Vegetables','Fresh Cabbage (Band Gobhi) sourced from local growers and prepared for market pickup.',110,'kg',50,'assets/img/products/cabbage-band-gobhi.jpg'),
(2,'Cauliflower (Phool Gobhi)','Vegetables','Fresh Cauliflower (Phool Gobhi) sourced from local growers and prepared for market pickup.',140,'kg',50,'assets/img/products/cauliflower-phool-gobhi.jpg'),
(2,'Turnip (Shalgam)','Vegetables','Fresh Turnip (Shalgam) sourced from local growers and prepared for market pickup.',130,'kg',50,'assets/img/products/turnip-shalgam.jpg'),
(2,'Radish (Mooli)','Vegetables','Fresh Radish (Mooli) sourced from local growers and prepared for market pickup.',100,'kg',50,'assets/img/products/radish-mooli.jpg'),
(2,'Tinda (Apple Gourd)','Vegetables','Fresh Tinda (Apple Gourd) sourced from local growers and prepared for market pickup.',160,'kg',50,'assets/img/products/tinda-apple-gourd.jpg'),
(2,'Zucchini','Vegetables','Fresh Zucchini sourced from local growers and prepared for market pickup.',280,'kg',50,'assets/img/products/zucchini.jpg'),
(2,'Sweet Corn','Vegetables','Fresh Sweet Corn sourced from local growers and prepared for market pickup.',180,'kg',50,'assets/img/products/sweet-corn.jpg'),
(2,'Red Chilli','Vegetables','Fresh Red Chilli sourced from local growers and prepared for market pickup.',260,'kg',50,'assets/img/products/red-chilli.jpg'),
(2,'Spinach (Palak)','Leafy Greens','Fresh Spinach (Palak) sourced from local growers and prepared for market pickup.',80,'bunch',50,'assets/img/products/spinach-palak.jpg'),
(2,'Fresh Methi','Leafy Greens','Fresh Fresh Methi sourced from local growers and prepared for market pickup.',140,'bunch',50,'assets/img/products/fresh-methi.jpg'),
(2,'Mustard Greens (Sarson)','Leafy Greens','Fresh Mustard Greens (Sarson) sourced from local growers and prepared for market pickup.',120,'bunch',50,'assets/img/products/mustard-greens-sarson.jpg'),
(2,'Bathua','Leafy Greens','Fresh Bathua sourced from local growers and prepared for market pickup.',100,'bunch',50,'assets/img/products/bathua.jpg'),
(2,'Kale','Leafy Greens','Fresh Kale sourced from local growers and prepared for market pickup.',350,'bunch',50,'assets/img/products/kale.jpg'),
(2,'Coriander (Dhaniya)','Herbs','Fresh Coriander (Dhaniya) sourced from local growers and prepared for market pickup.',60,'bunch',50,'assets/img/products/coriander-dhaniya.jpg'),
(2,'Mint (Pudina)','Herbs','Fresh Mint (Pudina) sourced from local growers and prepared for market pickup.',30,'bunch',50,'assets/img/products/mint-pudina.jpg'),
(2,'Spring Onion (Hari Pyaz)','Herbs','Fresh Spring Onion (Hari Pyaz) sourced from local growers and prepared for market pickup.',100,'bunch',50,'assets/img/products/spring-onion-hari-pyaz.jpg'),
(2,'Curry Leaves (Kari Patta)','Herbs','Fresh Curry Leaves (Kari Patta) sourced from local growers and prepared for market pickup.',50,'bunch',50,'assets/img/products/curry-leaves-kari-patta.jpg'),
(2,'Parsley','Herbs','Fresh Parsley sourced from local growers and prepared for market pickup.',220,'bunch',50,'assets/img/products/parsley.jpg'),
(2,'Basil','Herbs','Fresh Basil sourced from local growers and prepared for market pickup.',220,'bunch',50,'assets/img/products/basil.jpg'),
(2,'Lettuce','Salad','Fresh Lettuce sourced from local growers and prepared for market pickup.',120,'head',50,'assets/img/products/lettuce.jpg'),
(2,'Iceberg Lettuce','Salad','Fresh Iceberg Lettuce sourced from local growers and prepared for market pickup.',180,'head',50,'assets/img/products/iceberg-lettuce.jpg'),
(2,'Cherry Tomatoes','Salad','Fresh Cherry Tomatoes sourced from local growers and prepared for market pickup.',420,'kg',50,'assets/img/products/cherry-tomatoes.jpg'),
(2,'Red Cabbage','Salad','Fresh Red Cabbage sourced from local growers and prepared for market pickup.',180,'kg',50,'assets/img/products/red-cabbage.jpg'),
(2,'Celery','Salad','Fresh Celery sourced from local growers and prepared for market pickup.',250,'bunch',50,'assets/img/products/celery.jpg'),
(2,'Mangoes (Chaunsa)','Fruits','Fresh Mangoes (Chaunsa) sourced from local growers and prepared for market pickup.',520,'kg',50,'assets/img/products/mangoes-chaunsa.jpg'),
(2,'Mangoes (Sindhri)','Fruits','Fresh Mangoes (Sindhri) sourced from local growers and prepared for market pickup.',450,'kg',50,'assets/img/products/mangoes-sindhri.jpg'),
(2,'Bananas (Kela)','Fruits','Fresh Bananas (Kela) sourced from local growers and prepared for market pickup.',190,'dozen',50,'assets/img/products/bananas-kela.jpg'),
(2,'Apples (Seb)','Fruits','Fresh Apples (Seb) sourced from local growers and prepared for market pickup.',480,'kg',50,'assets/img/products/apples-seb.jpg'),
(2,'Kinnow Oranges','Fruits','Fresh Kinnow Oranges sourced from local growers and prepared for market pickup.',320,'dozen',50,'assets/img/products/kinnow-oranges.jpg'),
(2,'Guava (Amrood)','Fruits','Fresh Guava (Amrood) sourced from local growers and prepared for market pickup.',260,'kg',50,'assets/img/products/guava-amrood.jpg'),
(2,'Watermelon (Tarbooz)','Fruits','Fresh Watermelon (Tarbooz) sourced from local growers and prepared for market pickup.',100,'kg',50,'assets/img/products/watermelon-tarbooz.jpg'),
(2,'Papaya','Fruits','Fresh Papaya sourced from local growers and prepared for market pickup.',220,'kg',50,'assets/img/products/papaya.jpg'),
(2,'Strawberries','Fruits','Fresh Strawberries sourced from local growers and prepared for market pickup.',650,'kg',50,'assets/img/products/strawberries.jpg'),
(2,'Grapes (Angoor)','Fruits','Fresh Grapes (Angoor) sourced from local growers and prepared for market pickup.',420,'kg',50,'assets/img/products/grapes-angoor.jpg'),
(2,'Peaches (Aaroo)','Fruits','Fresh Peaches (Aaroo) sourced from local growers and prepared for market pickup.',450,'kg',50,'assets/img/products/peaches-aaroo.jpg'),
(2,'Pomegranate (Anar)','Fruits','Fresh Pomegranate (Anar) sourced from local growers and prepared for market pickup.',620,'kg',50,'assets/img/products/pomegranate-anar.jpg'),
(2,'Pineapple','Fruits','Fresh Pineapple sourced from local growers and prepared for market pickup.',480,'piece',50,'assets/img/products/pineapple.jpg'),
(2,'Dragon Fruit','Fruits','Fresh Dragon Fruit sourced from local growers and prepared for market pickup.',900,'kg',50,'assets/img/products/dragon-fruit.jpg'),
(2,'Chikoo','Fruits','Fresh Chikoo sourced from local growers and prepared for market pickup.',360,'kg',50,'assets/img/products/chikoo.jpg'),
(2,'Plums (Aloo Bukhara)','Fruits','Fresh Plums (Aloo Bukhara) sourced from local growers and prepared for market pickup.',480,'kg',50,'assets/img/products/plums-aloo-bukhara.jpg'),
(2,'Muskmelon (Kharbooza)','Fruits','Fresh Muskmelon (Kharbooza) sourced from local growers and prepared for market pickup.',180,'kg',50,'assets/img/products/muskmelon-kharbooza.jpg'),
(2,'Farm Fresh Eggs','Dairy & Eggs','Fresh Farm Fresh Eggs sourced from local growers and prepared for market pickup.',360,'dozen',50,'assets/img/products/farm-fresh-eggs.jpg'),
(2,'Fresh Milk','Dairy & Eggs','Fresh Fresh Milk sourced from local growers and prepared for market pickup.',220,'litre',50,'assets/img/products/fresh-milk.jpg'),
(2,'Fresh Yogurt (Dahi)','Dairy & Eggs','Fresh Fresh Yogurt (Dahi) sourced from local growers and prepared for market pickup.',280,'kg',50,'assets/img/products/fresh-yogurt-dahi.jpg'),
(2,'Farm Butter','Dairy & Eggs','Fresh Farm Butter sourced from local growers and prepared for market pickup.',650,'kg',50,'assets/img/products/farm-butter.jpg'),
(2,'Fresh Cream','Dairy & Eggs','Fresh Fresh Cream sourced from local growers and prepared for market pickup.',500,'500ml',50,'assets/img/products/fresh-cream.jpg'),
(2,'Paneer','Dairy & Eggs','Fresh Paneer sourced from local growers and prepared for market pickup.',950,'kg',50,'assets/img/products/paneer.jpg'),
(2,'Desi Ghee','Dairy & Eggs','Fresh Desi Ghee sourced from local growers and prepared for market pickup.',1800,'kg',50,'assets/img/products/desi-ghee.jpg'),
(2,'Fresh Chicken','Poultry','Fresh Fresh Chicken sourced from local growers and prepared for market pickup.',820,'kg',50,'assets/img/products/fresh-chicken.jpg'),
(2,'Chicken Breast','Poultry','Fresh Chicken Breast sourced from local growers and prepared for market pickup.',980,'kg',50,'assets/img/products/chicken-breast.jpg'),
(2,'Chicken Leg Pieces','Poultry','Fresh Chicken Leg Pieces sourced from local growers and prepared for market pickup.',850,'kg',50,'assets/img/products/chicken-leg-pieces.jpg'),
(2,'Chicken Wings','Poultry','Fresh Chicken Wings sourced from local growers and prepared for market pickup.',780,'kg',50,'assets/img/products/chicken-wings.jpg'),
(2,'Beef Qeema','Meat','Fresh Beef Qeema sourced from local growers and prepared for market pickup.',1400,'kg',50,'assets/img/products/beef-qeema.jpg'),
(2,'Beef Boneless','Meat','Fresh Beef Boneless sourced from local growers and prepared for market pickup.',1550,'kg',50,'assets/img/products/beef-boneless.jpg'),
(2,'Mutton','Meat','Fresh Mutton sourced from local growers and prepared for market pickup.',2400,'kg',50,'assets/img/products/mutton.jpg'),
(2,'Mutton Chops','Meat','Fresh Mutton Chops sourced from local growers and prepared for market pickup.',2600,'kg',50,'assets/img/products/mutton-chops.jpg'),
(2,'Pomfret Fish','Seafood','Fresh Pomfret Fish sourced from local growers and prepared for market pickup.',1800,'kg',50,'assets/img/products/pomfret-fish.jpg'),
(2,'Rohu Fish','Seafood','Fresh Rohu Fish sourced from local growers and prepared for market pickup.',900,'kg',50,'assets/img/products/rohu-fish.jpg'),
(2,'Surmai Fish','Seafood','Fresh Surmai Fish sourced from local growers and prepared for market pickup.',2200,'kg',50,'assets/img/products/surmai-fish.jpg'),
(2,'Prawns','Seafood','Fresh Prawns sourced from local growers and prepared for market pickup.',2400,'kg',50,'assets/img/products/prawns.jpg'),
(2,'King Fish','Seafood','Fresh King Fish sourced from local growers and prepared for market pickup.',2000,'kg',50,'assets/img/products/king-fish.jpg'),
(2,'Basmati Rice','Staples','Fresh Basmati Rice sourced from local growers and prepared for market pickup.',520,'kg',50,'assets/img/products/basmati-rice.jpg'),
(2,'Whole Wheat Atta','Staples','Fresh Whole Wheat Atta sourced from local growers and prepared for market pickup.',280,'kg',50,'assets/img/products/whole-wheat-atta.jpg'),
(2,'Maash Dal','Staples','Fresh Maash Dal sourced from local growers and prepared for market pickup.',700,'kg',50,'assets/img/products/maash-dal.jpg'),
(2,'Masoor Dal','Staples','Fresh Masoor Dal sourced from local growers and prepared for market pickup.',680,'kg',50,'assets/img/products/masoor-dal.jpg'),
(2,'Moong Dal','Staples','Fresh Moong Dal sourced from local growers and prepared for market pickup.',720,'kg',50,'assets/img/products/moong-dal.jpg'),
(2,'Chana Dal','Staples','Fresh Chana Dal sourced from local growers and prepared for market pickup.',620,'kg',50,'assets/img/products/chana-dal.jpg'),
(2,'Chickpeas (Chana)','Staples','Fresh Chickpeas (Chana) sourced from local growers and prepared for market pickup.',520,'kg',50,'assets/img/products/chickpeas-chana.jpg'),
(2,'White Sugar','Staples','Fresh White Sugar sourced from local growers and prepared for market pickup.',180,'kg',50,'assets/img/products/white-sugar.jpg'),
(2,'Pink Salt','Staples','Fresh Pink Salt sourced from local growers and prepared for market pickup.',180,'kg',50,'assets/img/products/pink-salt.jpg'),
(2,'Fresh Honey','Pantry','Fresh Fresh Honey sourced from local growers and prepared for market pickup.',1400,'kg',50,'assets/img/products/fresh-honey.jpg'),
(2,'Cooking Oil','Pantry','Fresh Cooking Oil sourced from local growers and prepared for market pickup.',620,'litre',50,'assets/img/products/cooking-oil.jpg'),
(2,'Mustard Oil','Pantry','Fresh Mustard Oil sourced from local growers and prepared for market pickup.',720,'litre',50,'assets/img/products/mustard-oil.jpg'),
(2,'Peanut Butter','Pantry','Fresh Peanut Butter sourced from local growers and prepared for market pickup.',900,'jar',50,'assets/img/products/peanut-butter.jpg'),
(2,'Tomato Ketchup','Pantry','Fresh Tomato Ketchup sourced from local growers and prepared for market pickup.',420,'bottle',50,'assets/img/products/tomato-ketchup.jpg'),
(2,'Mixed Pickle','Pantry','Fresh Mixed Pickle sourced from local growers and prepared for market pickup.',500,'jar',50,'assets/img/products/mixed-pickle.jpg'),
(2,'Fresh Bread','Bakery','Fresh Fresh Bread sourced from local growers and prepared for market pickup.',180,'loaf',50,'assets/img/products/fresh-bread.jpg'),
(2,'Whole Wheat Bread','Bakery','Fresh Whole Wheat Bread sourced from local growers and prepared for market pickup.',220,'loaf',50,'assets/img/products/whole-wheat-bread.jpg'),
(2,'Burger Buns','Bakery','Fresh Burger Buns sourced from local growers and prepared for market pickup.',180,'pack',50,'assets/img/products/burger-buns.jpg'),
(2,'Rusks','Bakery','Fresh Rusks sourced from local growers and prepared for market pickup.',260,'pack',50,'assets/img/products/rusks.jpg'),
(2,'Fresh Croissants','Bakery','Fresh Fresh Croissants sourced from local growers and prepared for market pickup.',450,'pack',50,'assets/img/products/fresh-croissants.jpg'),
(2,'Almonds (Badam)','Dry Fruits','Fresh Almonds (Badam) sourced from local growers and prepared for market pickup.',1200,'kg',50,'assets/img/products/almonds-badam.jpg'),
(2,'Cashews (Kaju)','Dry Fruits','Fresh Cashews (Kaju) sourced from local growers and prepared for market pickup.',1800,'kg',50,'assets/img/products/cashews-kaju.jpg'),
(2,'Pistachios (Pista)','Dry Fruits','Fresh Pistachios (Pista) sourced from local growers and prepared for market pickup.',2200,'kg',50,'assets/img/products/pistachios-pista.jpg'),
(2,'Walnuts (Akhrot)','Dry Fruits','Fresh Walnuts (Akhrot) sourced from local growers and prepared for market pickup.',1900,'kg',50,'assets/img/products/walnuts-akhrot.jpg'),
(2,'Dates (Khajoor)','Dry Fruits','Fresh Dates (Khajoor) sourced from local growers and prepared for market pickup.',700,'kg',50,'assets/img/products/dates-khajoor.jpg'),
(2,'Raisins (Kishmish)','Dry Fruits','Fresh Raisins (Kishmish) sourced from local growers and prepared for market pickup.',900,'kg',50,'assets/img/products/raisins-kishmish.jpg'),
(2,'Fresh Sugarcane Juice','Beverages','Fresh Fresh Sugarcane Juice sourced from local growers and prepared for market pickup.',250,'litre',50,'assets/img/products/fresh-sugarcane-juice.jpg'),
(2,'Fresh Orange Juice','Beverages','Fresh Fresh Orange Juice sourced from local growers and prepared for market pickup.',450,'litre',50,'assets/img/products/fresh-orange-juice.jpg'),
(2,'Lemon Mint Drink','Beverages','Fresh Lemon Mint Drink sourced from local growers and prepared for market pickup.',300,'litre',50,'assets/img/products/lemon-mint-drink.jpg'),
(2,'Organic Tomatoes','Organic','Fresh Organic Tomatoes sourced from local growers and prepared for market pickup.',280,'kg',50,'assets/img/products/organic-tomatoes.jpg'),
(2,'Organic Spinach','Organic','Fresh Organic Spinach sourced from local growers and prepared for market pickup.',160,'bunch',50,'assets/img/products/organic-spinach.jpg'),
(2,'Organic Carrots','Organic','Fresh Organic Carrots sourced from local growers and prepared for market pickup.',260,'kg',50,'assets/img/products/organic-carrots.jpg'),
(2,'Organic Apples','Organic','Fresh Organic Apples sourced from local growers and prepared for market pickup.',650,'kg',44,'assets/img/products/organic-apples.jpg');



INSERT INTO market_products(market_id,product_id) VALUES
(1,1),
(6,1),
(1,2),
(6,2),
(1,3),
(6,3),
(1,4),
(6,4),
(1,5),
(6,5),
(1,6),
(6,6),
(1,7),
(6,7),
(1,8),
(6,8),
(1,9),
(6,9),
(1,10),
(6,10),
(1,11),
(6,11),
(1,12),
(6,12),
(1,13),
(6,13),
(1,14),
(6,14),
(1,15),
(6,15),
(1,16),
(6,16),
(1,17),
(6,17),
(1,18),
(6,18),
(1,19),
(6,19),
(1,20),
(6,20),
(1,21),
(6,21),
(1,22),
(6,22),
(1,23),
(6,23),
(1,24),
(6,24),
(1,25),
(6,25),
(1,26),
(6,26),
(1,27),
(6,27),
(1,28),
(6,28),
(1,29),
(6,29),
(1,30),
(6,30),
(1,31),
(6,31),
(1,32),
(6,32),
(1,33),
(6,33),
(1,34),
(6,34),
(1,35),
(6,35),
(1,36),
(6,36),
(1,37),
(6,37),
(1,38),
(6,38),
(1,39),
(6,39),
(1,40),
(6,40),
(2,41),
(6,41),
(2,42),
(6,42),
(2,43),
(6,43),
(2,44),
(6,44),
(2,45),
(6,45),
(2,46),
(6,46),
(2,47),
(6,47),
(2,48),
(6,48),
(2,49),
(6,49),
(2,50),
(6,50),
(2,51),
(6,51),
(2,52),
(6,52),
(2,53),
(6,53),
(2,54),
(6,54),
(2,55),
(6,55),
(2,56),
(6,56),
(2,57),
(6,57),
(5,58),
(6,58),
(5,59),
(6,59),
(5,60),
(6,60),
(5,61),
(6,61),
(5,62),
(6,62),
(5,63),
(6,63),
(5,64),
(6,64),
(4,65),
(6,65),
(4,66),
(6,66),
(4,67),
(6,67),
(4,68),
(6,68),
(3,69),
(6,69),
(3,70),
(6,70),
(3,71),
(6,71),
(3,72),
(6,72),
(3,73),
(6,73),
(3,74),
(6,74),
(3,75),
(6,75),
(3,76),
(6,76),
(3,77),
(6,77),
(5,78),
(6,78),
(5,79),
(6,79),
(5,80),
(6,80),
(5,81),
(6,81),
(5,82),
(6,82),
(5,83),
(6,83),
(5,84),
(6,84),
(5,85),
(6,85),
(5,86),
(6,86),
(5,87),
(6,87),
(5,88),
(6,88),
(5,89),
(6,89),
(5,90),
(6,90),
(5,91),
(6,91),
(5,92),
(6,92),
(5,93),
(6,93),
(5,94),
(6,94),
(5,95),
(6,95),
(5,96),
(6,96),
(5,97),
(6,97),
(2,98),
(6,98),
(2,99),
(6,99),
(2,100),
(6,100),
(2,101),
(6,101),
(2,102),
(6,102),
(2,103),
(6,103),
(5,104),
(6,104),
(5,105),
(6,105),
(5,106),
(6,106),
(5,107),
(6,107),
(5,108),
(6,108),
(5,109),
(6,109),
(2,110),
(6,110);

INSERT INTO shop_product_prices(shop_id,product_id,price,unit,price_note) VALUES
(1,1,169.2,'kg','Demo comparison price - confirm with shop'),
(7,1,175.5,'kg','Demo comparison price - confirm with shop'),
(8,1,181.8,'kg','Demo comparison price - confirm with shop'),
(1,2,84.6,'kg','Demo comparison price - confirm with shop'),
(7,2,87.75,'kg','Demo comparison price - confirm with shop'),
(8,2,90.9,'kg','Demo comparison price - confirm with shop'),
(1,3,112.8,'kg','Demo comparison price - confirm with shop'),
(7,3,117.0,'kg','Demo comparison price - confirm with shop'),
(8,3,121.2,'kg','Demo comparison price - confirm with shop'),
(1,4,103.4,'kg','Demo comparison price - confirm with shop'),
(7,4,107.25,'kg','Demo comparison price - confirm with shop'),
(8,4,111.1,'kg','Demo comparison price - confirm with shop'),
(1,5,178.6,'kg','Demo comparison price - confirm with shop'),
(7,5,185.25,'kg','Demo comparison price - confirm with shop'),
(8,5,191.9,'kg','Demo comparison price - confirm with shop'),
(1,6,263.2,'kg','Demo comparison price - confirm with shop'),
(7,6,273.0,'kg','Demo comparison price - confirm with shop'),
(8,6,282.8,'kg','Demo comparison price - confirm with shop'),
(1,7,235.0,'kg','Demo comparison price - confirm with shop'),
(7,7,243.75,'kg','Demo comparison price - confirm with shop'),
(8,7,252.5,'kg','Demo comparison price - confirm with shop'),
(1,8,141.0,'kg','Demo comparison price - confirm with shop'),
(7,8,146.25,'kg','Demo comparison price - confirm with shop'),
(8,8,151.5,'kg','Demo comparison price - confirm with shop'),
(1,9,329.0,'kg','Demo comparison price - confirm with shop'),
(7,9,341.25,'kg','Demo comparison price - confirm with shop'),
(8,9,353.5,'kg','Demo comparison price - confirm with shop'),
(1,10,300.8,'kg','Demo comparison price - confirm with shop'),
(7,10,312.0,'kg','Demo comparison price - confirm with shop'),
(8,10,323.2,'kg','Demo comparison price - confirm with shop'),
(1,11,169.2,'kg','Demo comparison price - confirm with shop'),
(7,11,175.5,'kg','Demo comparison price - confirm with shop'),
(8,11,181.8,'kg','Demo comparison price - confirm with shop'),
(1,12,141.0,'kg','Demo comparison price - confirm with shop'),
(7,12,146.25,'kg','Demo comparison price - confirm with shop'),
(8,12,151.5,'kg','Demo comparison price - confirm with shop'),
(1,13,159.8,'kg','Demo comparison price - confirm with shop'),
(7,13,165.75,'kg','Demo comparison price - confirm with shop'),
(8,13,171.7,'kg','Demo comparison price - confirm with shop'),
(1,14,112.8,'kg','Demo comparison price - confirm with shop'),
(7,14,117.0,'kg','Demo comparison price - confirm with shop'),
(8,14,121.2,'kg','Demo comparison price - confirm with shop'),
(1,15,122.2,'kg','Demo comparison price - confirm with shop'),
(7,15,126.75,'kg','Demo comparison price - confirm with shop'),
(8,15,131.3,'kg','Demo comparison price - confirm with shop'),
(1,16,357.2,'kg','Demo comparison price - confirm with shop'),
(7,16,370.5,'kg','Demo comparison price - confirm with shop'),
(8,16,383.8,'kg','Demo comparison price - confirm with shop'),
(1,17,103.4,'kg','Demo comparison price - confirm with shop'),
(7,17,107.25,'kg','Demo comparison price - confirm with shop'),
(8,17,111.1,'kg','Demo comparison price - confirm with shop'),
(1,18,131.6,'kg','Demo comparison price - confirm with shop'),
(7,18,136.5,'kg','Demo comparison price - confirm with shop'),
(8,18,141.4,'kg','Demo comparison price - confirm with shop'),
(1,19,122.2,'kg','Demo comparison price - confirm with shop'),
(7,19,126.75,'kg','Demo comparison price - confirm with shop'),
(8,19,131.3,'kg','Demo comparison price - confirm with shop'),
(1,20,94.0,'kg','Demo comparison price - confirm with shop'),
(7,20,97.5,'kg','Demo comparison price - confirm with shop'),
(8,20,101.0,'kg','Demo comparison price - confirm with shop'),
(1,21,150.4,'kg','Demo comparison price - confirm with shop'),
(7,21,156.0,'kg','Demo comparison price - confirm with shop'),
(8,21,161.6,'kg','Demo comparison price - confirm with shop'),
(1,22,263.2,'kg','Demo comparison price - confirm with shop'),
(7,22,273.0,'kg','Demo comparison price - confirm with shop'),
(8,22,282.8,'kg','Demo comparison price - confirm with shop'),
(1,23,169.2,'kg','Demo comparison price - confirm with shop'),
(7,23,175.5,'kg','Demo comparison price - confirm with shop'),
(8,23,181.8,'kg','Demo comparison price - confirm with shop'),
(1,24,244.4,'kg','Demo comparison price - confirm with shop'),
(7,24,253.5,'kg','Demo comparison price - confirm with shop'),
(8,24,262.6,'kg','Demo comparison price - confirm with shop'),
(7,25,75.2,'bunch','Demo comparison price - confirm with shop'),
(8,25,78.0,'bunch','Demo comparison price - confirm with shop'),
(9,25,80.8,'bunch','Demo comparison price - confirm with shop'),
(7,26,131.6,'bunch','Demo comparison price - confirm with shop'),
(8,26,136.5,'bunch','Demo comparison price - confirm with shop'),
(9,26,141.4,'bunch','Demo comparison price - confirm with shop'),
(7,27,112.8,'bunch','Demo comparison price - confirm with shop'),
(8,27,117.0,'bunch','Demo comparison price - confirm with shop'),
(9,27,121.2,'bunch','Demo comparison price - confirm with shop'),
(7,28,94.0,'bunch','Demo comparison price - confirm with shop'),
(8,28,97.5,'bunch','Demo comparison price - confirm with shop'),
(9,28,101.0,'bunch','Demo comparison price - confirm with shop'),
(7,29,329.0,'bunch','Demo comparison price - confirm with shop'),
(8,29,341.25,'bunch','Demo comparison price - confirm with shop'),
(9,29,353.5,'bunch','Demo comparison price - confirm with shop'),
(7,30,56.4,'bunch','Demo comparison price - confirm with shop'),
(8,30,58.5,'bunch','Demo comparison price - confirm with shop'),
(9,30,60.6,'bunch','Demo comparison price - confirm with shop'),
(7,31,28.2,'bunch','Demo comparison price - confirm with shop'),
(8,31,29.25,'bunch','Demo comparison price - confirm with shop'),
(9,31,30.3,'bunch','Demo comparison price - confirm with shop'),
(7,32,94.0,'bunch','Demo comparison price - confirm with shop'),
(8,32,97.5,'bunch','Demo comparison price - confirm with shop'),
(9,32,101.0,'bunch','Demo comparison price - confirm with shop'),
(7,33,47.0,'bunch','Demo comparison price - confirm with shop'),
(8,33,48.75,'bunch','Demo comparison price - confirm with shop'),
(9,33,50.5,'bunch','Demo comparison price - confirm with shop'),
(7,34,206.8,'bunch','Demo comparison price - confirm with shop'),
(8,34,214.5,'bunch','Demo comparison price - confirm with shop'),
(9,34,222.2,'bunch','Demo comparison price - confirm with shop'),
(7,35,206.8,'bunch','Demo comparison price - confirm with shop'),
(8,35,214.5,'bunch','Demo comparison price - confirm with shop'),
(9,35,222.2,'bunch','Demo comparison price - confirm with shop'),
(7,36,112.8,'head','Demo comparison price - confirm with shop'),
(8,36,117.0,'head','Demo comparison price - confirm with shop'),
(9,36,121.2,'head','Demo comparison price - confirm with shop'),
(7,37,169.2,'head','Demo comparison price - confirm with shop'),
(8,37,175.5,'head','Demo comparison price - confirm with shop'),
(9,37,181.8,'head','Demo comparison price - confirm with shop'),
(7,38,394.8,'kg','Demo comparison price - confirm with shop'),
(8,38,409.5,'kg','Demo comparison price - confirm with shop'),
(9,38,424.2,'kg','Demo comparison price - confirm with shop'),
(7,39,169.2,'kg','Demo comparison price - confirm with shop'),
(8,39,175.5,'kg','Demo comparison price - confirm with shop'),
(9,39,181.8,'kg','Demo comparison price - confirm with shop'),
(7,40,235.0,'bunch','Demo comparison price - confirm with shop'),
(8,40,243.75,'bunch','Demo comparison price - confirm with shop'),
(9,40,252.5,'bunch','Demo comparison price - confirm with shop'),
(2,41,488.8,'kg','Demo comparison price - confirm with shop'),
(3,41,507.0,'kg','Demo comparison price - confirm with shop'),
(7,41,525.2,'kg','Demo comparison price - confirm with shop'),
(2,42,423.0,'kg','Demo comparison price - confirm with shop'),
(3,42,438.75,'kg','Demo comparison price - confirm with shop'),
(7,42,454.5,'kg','Demo comparison price - confirm with shop'),
(2,43,178.6,'dozen','Demo comparison price - confirm with shop'),
(3,43,185.25,'dozen','Demo comparison price - confirm with shop'),
(7,43,191.9,'dozen','Demo comparison price - confirm with shop'),
(2,44,451.2,'kg','Demo comparison price - confirm with shop'),
(3,44,468.0,'kg','Demo comparison price - confirm with shop'),
(7,44,484.8,'kg','Demo comparison price - confirm with shop'),
(2,45,300.8,'dozen','Demo comparison price - confirm with shop'),
(3,45,312.0,'dozen','Demo comparison price - confirm with shop'),
(7,45,323.2,'dozen','Demo comparison price - confirm with shop'),
(2,46,244.4,'kg','Demo comparison price - confirm with shop'),
(3,46,253.5,'kg','Demo comparison price - confirm with shop'),
(7,46,262.6,'kg','Demo comparison price - confirm with shop'),
(2,47,94.0,'kg','Demo comparison price - confirm with shop'),
(3,47,97.5,'kg','Demo comparison price - confirm with shop'),
(7,47,101.0,'kg','Demo comparison price - confirm with shop'),
(2,48,206.8,'kg','Demo comparison price - confirm with shop'),
(3,48,214.5,'kg','Demo comparison price - confirm with shop'),
(7,48,222.2,'kg','Demo comparison price - confirm with shop'),
(2,49,611.0,'kg','Demo comparison price - confirm with shop'),
(3,49,633.75,'kg','Demo comparison price - confirm with shop'),
(7,49,656.5,'kg','Demo comparison price - confirm with shop'),
(2,50,394.8,'kg','Demo comparison price - confirm with shop'),
(3,50,409.5,'kg','Demo comparison price - confirm with shop'),
(7,50,424.2,'kg','Demo comparison price - confirm with shop'),
(2,51,423.0,'kg','Demo comparison price - confirm with shop'),
(3,51,438.75,'kg','Demo comparison price - confirm with shop'),
(7,51,454.5,'kg','Demo comparison price - confirm with shop'),
(2,52,582.8,'kg','Demo comparison price - confirm with shop'),
(3,52,604.5,'kg','Demo comparison price - confirm with shop'),
(7,52,626.2,'kg','Demo comparison price - confirm with shop'),
(2,53,451.2,'piece','Demo comparison price - confirm with shop'),
(3,53,468.0,'piece','Demo comparison price - confirm with shop'),
(7,53,484.8,'piece','Demo comparison price - confirm with shop'),
(2,54,846.0,'kg','Demo comparison price - confirm with shop'),
(3,54,877.5,'kg','Demo comparison price - confirm with shop'),
(7,54,909.0,'kg','Demo comparison price - confirm with shop'),
(2,55,338.4,'kg','Demo comparison price - confirm with shop'),
(3,55,351.0,'kg','Demo comparison price - confirm with shop'),
(7,55,363.6,'kg','Demo comparison price - confirm with shop'),
(2,56,451.2,'kg','Demo comparison price - confirm with shop'),
(3,56,468.0,'kg','Demo comparison price - confirm with shop'),
(7,56,484.8,'kg','Demo comparison price - confirm with shop'),
(2,57,169.2,'kg','Demo comparison price - confirm with shop'),
(3,57,175.5,'kg','Demo comparison price - confirm with shop'),
(7,57,181.8,'kg','Demo comparison price - confirm with shop'),
(7,58,338.4,'dozen','Demo comparison price - confirm with shop'),
(8,58,351.0,'dozen','Demo comparison price - confirm with shop'),
(9,58,363.6,'dozen','Demo comparison price - confirm with shop'),
(7,59,206.8,'litre','Demo comparison price - confirm with shop'),
(8,59,214.5,'litre','Demo comparison price - confirm with shop'),
(9,59,222.2,'litre','Demo comparison price - confirm with shop'),
(7,60,263.2,'kg','Demo comparison price - confirm with shop'),
(8,60,273.0,'kg','Demo comparison price - confirm with shop'),
(9,60,282.8,'kg','Demo comparison price - confirm with shop'),
(7,61,611.0,'kg','Demo comparison price - confirm with shop'),
(8,61,633.75,'kg','Demo comparison price - confirm with shop'),
(9,61,656.5,'kg','Demo comparison price - confirm with shop'),
(7,62,470.0,'500ml','Demo comparison price - confirm with shop'),
(8,62,487.5,'500ml','Demo comparison price - confirm with shop'),
(9,62,505.0,'500ml','Demo comparison price - confirm with shop'),
(7,63,893.0,'kg','Demo comparison price - confirm with shop'),
(8,63,926.25,'kg','Demo comparison price - confirm with shop'),
(9,63,959.5,'kg','Demo comparison price - confirm with shop'),
(7,64,1692.0,'kg','Demo comparison price - confirm with shop'),
(8,64,1755.0,'kg','Demo comparison price - confirm with shop'),
(9,64,1818.0,'kg','Demo comparison price - confirm with shop'),
(5,65,770.8,'kg','Demo comparison price - confirm with shop'),
(6,65,799.5,'kg','Demo comparison price - confirm with shop'),
(7,65,828.2,'kg','Demo comparison price - confirm with shop'),
(5,66,921.2,'kg','Demo comparison price - confirm with shop'),
(6,66,955.5,'kg','Demo comparison price - confirm with shop'),
(7,66,989.8,'kg','Demo comparison price - confirm with shop'),
(5,67,799.0,'kg','Demo comparison price - confirm with shop'),
(6,67,828.75,'kg','Demo comparison price - confirm with shop'),
(7,67,858.5,'kg','Demo comparison price - confirm with shop'),
(5,68,733.2,'kg','Demo comparison price - confirm with shop'),
(6,68,760.5,'kg','Demo comparison price - confirm with shop'),
(7,68,787.8,'kg','Demo comparison price - confirm with shop'),
(4,69,1316.0,'kg','Demo comparison price - confirm with shop'),
(7,69,1365.0,'kg','Demo comparison price - confirm with shop'),
(9,69,1414.0,'kg','Demo comparison price - confirm with shop'),
(4,70,1457.0,'kg','Demo comparison price - confirm with shop'),
(7,70,1511.25,'kg','Demo comparison price - confirm with shop'),
(9,70,1565.5,'kg','Demo comparison price - confirm with shop'),
(4,71,2256.0,'kg','Demo comparison price - confirm with shop'),
(7,71,2340.0,'kg','Demo comparison price - confirm with shop'),
(9,71,2424.0,'kg','Demo comparison price - confirm with shop'),
(4,72,2444.0,'kg','Demo comparison price - confirm with shop'),
(7,72,2535.0,'kg','Demo comparison price - confirm with shop'),
(9,72,2626.0,'kg','Demo comparison price - confirm with shop'),
(7,73,1692.0,'kg','Demo comparison price - confirm with shop'),
(8,73,1755.0,'kg','Demo comparison price - confirm with shop'),
(9,73,1818.0,'kg','Demo comparison price - confirm with shop'),
(7,74,846.0,'kg','Demo comparison price - confirm with shop'),
(8,74,877.5,'kg','Demo comparison price - confirm with shop'),
(9,74,909.0,'kg','Demo comparison price - confirm with shop'),
(7,75,2068.0,'kg','Demo comparison price - confirm with shop'),
(8,75,2145.0,'kg','Demo comparison price - confirm with shop'),
(9,75,2222.0,'kg','Demo comparison price - confirm with shop'),
(7,76,2256.0,'kg','Demo comparison price - confirm with shop'),
(8,76,2340.0,'kg','Demo comparison price - confirm with shop'),
(9,76,2424.0,'kg','Demo comparison price - confirm with shop'),
(7,77,1880.0,'kg','Demo comparison price - confirm with shop'),
(8,77,1950.0,'kg','Demo comparison price - confirm with shop'),
(9,77,2020.0,'kg','Demo comparison price - confirm with shop'),
(7,78,488.8,'kg','Demo comparison price - confirm with shop'),
(8,78,507.0,'kg','Demo comparison price - confirm with shop'),
(9,78,525.2,'kg','Demo comparison price - confirm with shop'),
(7,79,263.2,'kg','Demo comparison price - confirm with shop'),
(8,79,273.0,'kg','Demo comparison price - confirm with shop'),
(9,79,282.8,'kg','Demo comparison price - confirm with shop'),
(7,80,658.0,'kg','Demo comparison price - confirm with shop'),
(8,80,682.5,'kg','Demo comparison price - confirm with shop'),
(9,80,707.0,'kg','Demo comparison price - confirm with shop'),
(7,81,639.2,'kg','Demo comparison price - confirm with shop'),
(8,81,663.0,'kg','Demo comparison price - confirm with shop'),
(9,81,686.8,'kg','Demo comparison price - confirm with shop'),
(7,82,676.8,'kg','Demo comparison price - confirm with shop'),
(8,82,702.0,'kg','Demo comparison price - confirm with shop'),
(9,82,727.2,'kg','Demo comparison price - confirm with shop'),
(7,83,582.8,'kg','Demo comparison price - confirm with shop'),
(8,83,604.5,'kg','Demo comparison price - confirm with shop'),
(9,83,626.2,'kg','Demo comparison price - confirm with shop'),
(7,84,488.8,'kg','Demo comparison price - confirm with shop'),
(8,84,507.0,'kg','Demo comparison price - confirm with shop'),
(9,84,525.2,'kg','Demo comparison price - confirm with shop'),
(7,85,169.2,'kg','Demo comparison price - confirm with shop'),
(8,85,175.5,'kg','Demo comparison price - confirm with shop'),
(9,85,181.8,'kg','Demo comparison price - confirm with shop'),
(7,86,169.2,'kg','Demo comparison price - confirm with shop'),
(8,86,175.5,'kg','Demo comparison price - confirm with shop'),
(9,86,181.8,'kg','Demo comparison price - confirm with shop'),
(7,87,1316.0,'kg','Demo comparison price - confirm with shop'),
(8,87,1365.0,'kg','Demo comparison price - confirm with shop'),
(9,87,1414.0,'kg','Demo comparison price - confirm with shop'),
(7,88,582.8,'litre','Demo comparison price - confirm with shop'),
(8,88,604.5,'litre','Demo comparison price - confirm with shop'),
(9,88,626.2,'litre','Demo comparison price - confirm with shop'),
(7,89,676.8,'litre','Demo comparison price - confirm with shop'),
(8,89,702.0,'litre','Demo comparison price - confirm with shop'),
(9,89,727.2,'litre','Demo comparison price - confirm with shop'),
(7,90,846.0,'jar','Demo comparison price - confirm with shop'),
(8,90,877.5,'jar','Demo comparison price - confirm with shop'),
(9,90,909.0,'jar','Demo comparison price - confirm with shop'),
(7,91,394.8,'bottle','Demo comparison price - confirm with shop'),
(8,91,409.5,'bottle','Demo comparison price - confirm with shop'),
(9,91,424.2,'bottle','Demo comparison price - confirm with shop'),
(7,92,470.0,'jar','Demo comparison price - confirm with shop'),
(8,92,487.5,'jar','Demo comparison price - confirm with shop'),
(9,92,505.0,'jar','Demo comparison price - confirm with shop'),
(7,93,169.2,'loaf','Demo comparison price - confirm with shop'),
(8,93,175.5,'loaf','Demo comparison price - confirm with shop'),
(9,93,181.8,'loaf','Demo comparison price - confirm with shop'),
(7,94,206.8,'loaf','Demo comparison price - confirm with shop'),
(8,94,214.5,'loaf','Demo comparison price - confirm with shop'),
(9,94,222.2,'loaf','Demo comparison price - confirm with shop'),
(7,95,169.2,'pack','Demo comparison price - confirm with shop'),
(8,95,175.5,'pack','Demo comparison price - confirm with shop'),
(9,95,181.8,'pack','Demo comparison price - confirm with shop'),
(7,96,244.4,'pack','Demo comparison price - confirm with shop'),
(8,96,253.5,'pack','Demo comparison price - confirm with shop'),
(9,96,262.6,'pack','Demo comparison price - confirm with shop'),
(7,97,423.0,'pack','Demo comparison price - confirm with shop'),
(8,97,438.75,'pack','Demo comparison price - confirm with shop'),
(9,97,454.5,'pack','Demo comparison price - confirm with shop'),
(2,98,1128.0,'kg','Demo comparison price - confirm with shop'),
(3,98,1170.0,'kg','Demo comparison price - confirm with shop'),
(7,98,1212.0,'kg','Demo comparison price - confirm with shop'),
(2,99,1692.0,'kg','Demo comparison price - confirm with shop'),
(3,99,1755.0,'kg','Demo comparison price - confirm with shop'),
(7,99,1818.0,'kg','Demo comparison price - confirm with shop'),
(2,100,2068.0,'kg','Demo comparison price - confirm with shop'),
(3,100,2145.0,'kg','Demo comparison price - confirm with shop'),
(7,100,2222.0,'kg','Demo comparison price - confirm with shop'),
(2,101,1786.0,'kg','Demo comparison price - confirm with shop'),
(3,101,1852.5,'kg','Demo comparison price - confirm with shop'),
(7,101,1919.0,'kg','Demo comparison price - confirm with shop'),
(2,102,658.0,'kg','Demo comparison price - confirm with shop'),
(3,102,682.5,'kg','Demo comparison price - confirm with shop'),
(7,102,707.0,'kg','Demo comparison price - confirm with shop'),
(2,103,846.0,'kg','Demo comparison price - confirm with shop'),
(3,103,877.5,'kg','Demo comparison price - confirm with shop'),
(7,103,909.0,'kg','Demo comparison price - confirm with shop'),
(7,104,235.0,'litre','Demo comparison price - confirm with shop'),
(8,104,243.75,'litre','Demo comparison price - confirm with shop'),
(9,104,252.5,'litre','Demo comparison price - confirm with shop'),
(7,105,423.0,'litre','Demo comparison price - confirm with shop'),
(8,105,438.75,'litre','Demo comparison price - confirm with shop'),
(9,105,454.5,'litre','Demo comparison price - confirm with shop'),
(7,106,282.0,'litre','Demo comparison price - confirm with shop'),
(8,106,292.5,'litre','Demo comparison price - confirm with shop'),
(9,106,303.0,'litre','Demo comparison price - confirm with shop'),
(7,107,263.2,'kg','Demo comparison price - confirm with shop'),
(8,107,273.0,'kg','Demo comparison price - confirm with shop'),
(9,107,282.8,'kg','Demo comparison price - confirm with shop'),
(7,108,150.4,'bunch','Demo comparison price - confirm with shop'),
(8,108,156.0,'bunch','Demo comparison price - confirm with shop'),
(9,108,161.6,'bunch','Demo comparison price - confirm with shop'),
(7,109,244.4,'kg','Demo comparison price - confirm with shop'),
(8,109,253.5,'kg','Demo comparison price - confirm with shop'),
(9,109,262.6,'kg','Demo comparison price - confirm with shop'),
(7,110,611.0,'kg','Demo comparison price - confirm with shop'),
(8,110,633.75,'kg','Demo comparison price - confirm with shop'),
(9,110,656.5,'kg','Demo comparison price - confirm with shop');

INSERT INTO reviews(product_id,customer_id,rating,comment) VALUES
(1,3,5,'Fresh and good quality.');
