<?php require 'config/config.php'; layout_header('Home');
$products = db()->query("SELECT p.*, u.username AS farmer_name FROM products p JOIN users u ON u.id=p.farmer_id WHERE p.stock_quantity>0 ORDER BY p.id DESC LIMIT 8")->fetchAll();
$markets = db()->query("SELECT m.*,COUNT(mp.product_id) product_count FROM markets m LEFT JOIN market_products mp ON mp.market_id=m.id GROUP BY m.id ORDER BY m.id DESC LIMIT 6")->fetchAll();
$shops = db()->query("SELECT s.*,COUNT(DISTINCT spp.product_id) product_count,MIN(spp.price) low_price FROM shops s LEFT JOIN shop_product_prices spp ON spp.shop_id=s.id GROUP BY s.id ORDER BY s.id LIMIT 6")->fetchAll();
?>
<section class="hero p-5 rounded-4 mb-5"><div class="row align-items-center"><div class="col-lg-7"><span class="badge bg-light text-success mb-3">Fresh • Local • Nearby</span><h1 class="display-4 fw-bold">Your local markets, shops & fresh products — all in one place.</h1><p class="lead">Choose vegetables, fruits, meat or chicken markets, check nearby shops and compare listed prices before pickup.</p><a class="btn btn-success btn-lg me-2" href="products.php">Browse products</a><a class="btn btn-outline-dark btn-lg" href="markets.php">Find markets & shops</a></div><div class="col-lg-5"><div class="hero-card"><img src="assets/img/market-hero.jpg" alt="Fresh local market produce"><div class="hero-caption">Fresh produce • Local shops • Easy pickup</div></div></div></div></section>
<div class="row g-3 mb-5"><div class="col-md-3"><a class="quick-category" href="markets.php?type=vegetable">🥬<strong>Vegetable Market</strong><small>Sabzi & greens</small></a></div><div class="col-md-3"><a class="quick-category" href="markets.php?type=fruit">🍎<strong>Fruit Market</strong><small>Seasonal fruits</small></a></div><div class="col-md-3"><a class="quick-category" href="markets.php?type=meat">🥩<strong>Meat Market</strong><small>Beef & mutton</small></a></div><div class="col-md-3"><a class="quick-category" href="markets.php?type=chicken">🍗<strong>Chicken Market</strong><small>Chicken shops</small></a></div></div>
<div class="d-flex justify-content-between align-items-center mb-3"><h2 class="section-title">Markets in Karachi</h2><a href="markets.php">View all</a></div><div class="row g-3 mb-5"><?php foreach($markets as $m): ?><div class="col-md-6 col-lg-4"><div class="card p-3 h-100"><span class="badge bg-light text-success mb-2">Market</span><h5><?=e($m['market_name'])?></h5><p class="small text-muted mb-1">📍 <?=e($m['address'])?></p><small><?=e((string)$m['product_count'])?> products • <?=e($m['operating_days'])?></small></div></div><?php endforeach; ?></div>
<div class="d-flex justify-content-between align-items-center mb-3"><h2 class="section-title">Shops & lower listed prices</h2><button class="btn btn-sm btn-success" onclick="findHomeNearMe()">📍 Near me</button></div><div class="row g-3 mb-5" id="homeShops"><?php foreach($shops as $s): ?><div class="col-md-6 col-lg-4 home-shop" data-lat="<?=$s['latitude']?>" data-lng="<?=$s['longitude']?>"><div class="card p-3 h-100"><span class="badge bg-success-subtle text-success mb-2"><?=e(ucwords(str_replace('_',' ',$s['shop_type'])))?></span><h5><?=e($s['shop_name'])?></h5><p class="small mb-1">📍 <?=e($s['area'])?></p><strong class="text-success">From <?=money((float)$s['low_price'])?></strong><small class="text-muted d-block mt-1">Lowest listed demo price; confirm at shop.</small><a href="markets.php" class="btn btn-outline-success mt-3">View shop & map</a></div></div><?php endforeach; ?></div>
<div class="d-flex justify-content-between align-items-center mb-3"><h2 class="section-title">Fresh this week</h2><a href="products.php">View all</a></div><div class="row g-4"><?php foreach($products as $p): ?><div class="col-md-6 col-lg-3"><div class="card h-100 product-card"><div class="product-img"><img src="<?=e(product_image($p['name'],$p['category'],$p['image_url'] ?? ''))?>" alt="<?=e($p['name'])?>" loading="lazy" onerror="this.onerror=null;this.src='assets/img-placeholder.svg';"></div><div class="card-body"><small class="text-muted"><?=e($p['category'])?></small><h5><?=e($p['name'])?></h5><p class="small text-muted mb-2">by <?=e($p['farmer_name'])?></p><strong class="price"><?=money((float)$p['price'])?></strong> / <?=e($p['unit'])?><a class="btn btn-outline-success w-100 mt-3" href="product.php?id=<?=$p['id']?>">View</a></div></div></div><?php endforeach; ?></div>
<script>function hh(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,x=r(c-a),y=r(d-b),h=Math.sin(x/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(h));}function findHomeNearMe(){if(!navigator.geolocation){alert('Location not supported.');return;}navigator.geolocation.getCurrentPosition(p=>{[...document.querySelectorAll('.home-shop')].sort((x,y)=>hh(p.coords.latitude,p.coords.longitude,+x.dataset.lat,+x.dataset.lng)-hh(p.coords.latitude,p.coords.longitude,+y.dataset.lat,+y.dataset.lng)).forEach(x=>document.getElementById('homeShops').appendChild(x));alert('Nearby shops sorted from nearest to farthest.');},()=>alert('Please allow location access.'));}</script>
<?php layout_footer(); ?>
