<?php require 'config/config.php'; $id=(int)($_GET['id']??0);
$s=db()->prepare("SELECT p.*,u.username farmer_name,u.id farmer_id FROM products p JOIN users u ON u.id=p.farmer_id WHERE p.id=?");$s->execute([$id]);$p=$s->fetch();if(!$p)exit('Product not found');
if($_SERVER['REQUEST_METHOD']==='POST'){require_login();check_csrf();$qty=max(1,(int)$_POST['quantity']);if($qty>$p['stock_quantity']){flash('danger','Not enough stock.');}else{$_SESSION['cart'][$id]=($_SESSION['cart'][$id]??0)+$qty;flash('success','Product added to cart.');redirect('cart.php');}}
$reviews=db()->prepare("SELECT r.*,u.username FROM reviews r JOIN users u ON u.id=r.customer_id WHERE r.product_id=? ORDER BY r.id DESC");$reviews->execute([$id]);$reviews=$reviews->fetchAll();
layout_header($p['name']);?>
<div class="row g-4"><div class="col-md-5"><div class="product-big"><img src="<?=e(product_image($p['name'],$p['category'],$p['image_url'] ?? ''))?>" alt="<?=e($p['name'])?>"></div></div><div class="col-md-7"><span class="badge bg-success"><?=e($p['category'])?></span><h1><?=e($p['name'])?></h1><p class="text-muted">Sold by <?=e($p['farmer_name'])?></p><p><?=nl2br(e($p['description']))?></p><h3><?=money((float)$p['price'])?> <small class="fs-6">/ <?=e($p['unit'])?></small></h3><p>Available: <?=$p['stock_quantity']?></p>
<?php $ps=db()->prepare("SELECT s.shop_name,s.shop_type,s.area,s.latitude,s.longitude,spp.price,spp.unit FROM shop_product_prices spp JOIN shops s ON s.id=spp.shop_id WHERE spp.product_id=? ORDER BY spp.price ASC");$ps->execute([$id]);$shopPrices=$ps->fetchAll(); ?>
<?php if($shopPrices): ?><div class="mt-4"><h5>Where to buy this product</h5><div class="row g-2"><?php foreach($shopPrices as $sp): ?><div class="col-md-6"><div class="border rounded-3 p-2 h-100"><div class="d-flex justify-content-between gap-2"><strong><?=e($sp['shop_name'])?></strong><span class="text-success fw-bold"><?=money((float)$sp['price'])?>/<?=e($sp['unit'])?></span></div><small class="text-muted">📍 <?=e($sp['area'])?> • <?=e(ucwords(str_replace('_',' ',$sp['shop_type'])))?></small><br><a target="_blank" href="https://www.openstreetmap.org/?mlat=<?=$sp['latitude']?>&mlon=<?=$sp['longitude']?>#map=16/<?=$sp['latitude']?>/<?=$sp['longitude']?>">Open location</a></div></div><?php endforeach; ?></div><small class="text-muted d-block mt-2">Listed comparison prices are demo values; confirm current shop price before purchase.</small></div><?php endif; ?>
<form method="post" class="d-flex gap-2"><?=csrf_field()?><input type="number" name="quantity" min="1" max="<?=$p['stock_quantity']?>" value="1" class="form-control" style="max-width:120px"><button class="btn btn-success">Add to cart</button></form></div></div>
<h3 class="mt-5">Reviews</h3><?php foreach($reviews as $r):?><div class="border-bottom py-3"><strong><?=e($r['username'])?></strong> — <?=str_repeat('★',(int)$r['rating'])?><p class="mb-0"><?=e($r['comment'])?></p></div><?php endforeach;?>
<?php if(user() && user()['role']==='customer'):?><form method="post" action="review.php" class="mt-4"><input type="hidden" name="product_id" value="<?=$id?>"><?=csrf_field()?><select name="rating" class="form-select mb-2" style="max-width:200px"><option value="5">5 stars</option><option value="4">4 stars</option><option value="3">3 stars</option><option value="2">2 stars</option><option value="1">1 star</option></select><textarea name="comment" class="form-control mb-2" placeholder="Your review"></textarea><button class="btn btn-outline-success">Submit review</button></form><?php endif;?>
<?php layout_footer(); ?>